import { Profile } from './types';

export const MOCK_PROFILES: Profile[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    age: 26,
    gender: 'female',
    bio: 'Software engineer by day, amateur chef by night. I believe the best conversations happen over good food. Looking for someone who appreciates both a well-written function and a well-seasoned curry.',
    interests: ['Cooking', 'Hiking', 'Photography', 'Tech', 'Travel'],
    location: 'San Francisco, CA',
    photos: ['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=500&fit=crop'],
    lookingFor: 'Something meaningful — open to seeing where things go',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Alex Chen',
    age: 29,
    gender: 'male',
    bio: 'Rock climber, bookworm, and unrepentant dog person. Currently reading everything by Haruki Murakami. My ideal weekend involves a summit and a sunset.',
    interests: ['Rock Climbing', 'Reading', 'Dogs', 'Music', 'Coffee'],
    location: 'Portland, OR',
    photos: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop'],
    lookingFor: 'A genuine connection with someone who loves the outdoors',
    createdAt: '2024-02-01',
  },
  {
    id: '3',
    name: 'Maya Johnson',
    age: 24,
    gender: 'female',
    bio: 'Yoga instructor and plant mom with too many succulents. I write poetry on napkins and sing in the shower. Life is short — let\'s make it beautiful.',
    interests: ['Yoga', 'Plants', 'Poetry', 'Sustainability', 'Art'],
    location: 'Austin, TX',
    photos: ['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=500&fit=crop'],
    lookingFor: 'Someone kind, creative, and not afraid to be vulnerable',
    createdAt: '2024-02-10',
  },
  {
    id: '4',
    name: 'James Rivera',
    age: 31,
    gender: 'male',
    bio: 'ER doctor who somehow still believes in romance. When I\'m not saving lives, I\'m attempting to learn salsa dancing. Emphasis on "attempting."',
    interests: ['Dancing', 'Medicine', 'Cooking', 'Movies', 'Running'],
    location: 'New York, NY',
    photos: ['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=500&fit=crop'],
    lookingFor: 'A partner in crime who doesn\'t mind odd schedules',
    createdAt: '2024-01-20',
  },
  {
    id: '5',
    name: 'Aisha Patel',
    age: 27,
    gender: 'female',
    bio: 'Product designer obsessed with clean interfaces and messy paintbrushes. Weekend warrior at farmers markets. I judge restaurants by their dessert menu.',
    interests: ['Design', 'Painting', 'Food', 'Cycling', 'Museums'],
    location: 'Seattle, WA',
    photos: ['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=500&fit=crop'],
    lookingFor: 'Someone curious, funny, and a little nerdy',
    createdAt: '2024-03-01',
  },
  {
    id: '6',
    name: 'Ryan Park',
    age: 28,
    gender: 'male',
    bio: 'Architect who builds things during the day and Lego sets at night. I have strong opinions about fonts and even stronger opinions about pizza toppings.',
    interests: ['Architecture', 'Lego', 'Typography', 'Gaming', 'Skateboarding'],
    location: 'Chicago, IL',
    photos: ['https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=500&fit=crop'],
    lookingFor: 'Someone who can debate pineapple on pizza for hours',
    createdAt: '2024-02-15',
  },
  {
    id: '7',
    name: 'Sofia Martinez',
    age: 25,
    gender: 'female',
    bio: 'Marine biologist with a slight obsession with octopuses. I\'ve lived in 4 countries and speak 3 languages. Always planning my next dive trip.',
    interests: ['Diving', 'Travel', 'Languages', 'Documentaries', 'Surfing'],
    location: 'San Diego, CA',
    photos: ['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=500&fit=crop'],
    lookingFor: 'An adventure buddy with a curious mind',
    createdAt: '2024-01-28',
  },
  {
    id: '8',
    name: 'Ethan Williams',
    age: 30,
    gender: 'male',
    bio: 'Freelance photographer chasing golden hour. I make a mean espresso and an even meaner playlist. Dog dad to a rescued greyhound named Rocket.',
    interests: ['Photography', 'Coffee', 'Music', 'Dogs', 'Vintage Cars'],
    location: 'Denver, CO',
    photos: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=500&fit=crop'],
    lookingFor: 'Someone who appreciates the small beautiful moments',
    createdAt: '2024-02-20',
  },
  {
    id: '9',
    name: 'Luna Kim',
    age: 23,
    gender: 'female',
    bio: 'Data scientist who reads tarot cards for fun (the irony isn\'t lost on me). I make playlists for every mood and bake when I\'m stressed. Currently learning ceramics.',
    interests: ['Data Science', 'Tarot', 'Baking', 'Ceramics', 'Anime'],
    location: 'Los Angeles, CA',
    photos: ['https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=500&fit=crop'],
    lookingFor: 'Someone thoughtful who likes deep conversations',
    createdAt: '2024-03-05',
  },
  {
    id: '10',
    name: 'Marcus Thompson',
    age: 33,
    gender: 'male',
    bio: 'High school English teacher and weekend trail runner. I believe in the power of a good story. Currently writing a novel that may never be finished, and I\'m okay with that.',
    interests: ['Writing', 'Running', 'Teaching', 'Board Games', 'Hiking'],
    location: 'Nashville, TN',
    photos: ['https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=500&fit=crop'],
    lookingFor: 'A fellow storyteller who loves laughing',
    createdAt: '2024-01-10',
  },
  {
    id: '11',
    name: 'Zara Ali',
    age: 28,
    gender: 'female',
    bio: 'Startup founder building something cool (can\'t say what yet). I run on chai, ambition, and carefully curated Spotify playlists. Weekend potter — the clay kind, not Harry.',
    interests: ['Startups', 'Pottery', 'Music', 'Chai', 'Traveling'],
    location: 'Boston, MA',
    photos: ['https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=500&fit=crop'],
    lookingFor: 'Someone driven with a great sense of humor',
    createdAt: '2024-02-25',
  },
  {
    id: '12',
    name: 'Daniel Nakamura',
    age: 27,
    gender: 'male',
    bio: 'Jazz pianist and part-time barista. I can make latte art that looks like your pet. Life motto: stay curious, stay kind, and always tip your server.',
    interests: ['Jazz', 'Coffee', 'Piano', 'Cooking', 'Vinyl Records'],
    location: 'Brooklyn, NY',
    photos: ['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=500&fit=crop'],
    lookingFor: 'Someone warm who enjoys live music and long walks',
    createdAt: '2024-03-10',
  },
];

// Current mock user (simulating logged in)
export const MOCK_CURRENT_USER: Profile = {
  id: 'current-user',
  name: 'You',
  age: 25,
  gender: 'female',
  bio: '',
  interests: [],
  location: '',
  photos: [],
  lookingFor: '',
  createdAt: new Date().toISOString(),
};

export const ALL_INTERESTS = [
  'Cooking', 'Hiking', 'Photography', 'Tech', 'Travel',
  'Rock Climbing', 'Reading', 'Dogs', 'Music', 'Coffee',
  'Yoga', 'Plants', 'Poetry', 'Sustainability', 'Art',
  'Dancing', 'Movies', 'Running', 'Design', 'Painting',
  'Food', 'Cycling', 'Museums', 'Gaming', 'Surfing',
  'Languages', 'Baking', 'Ceramics', 'Anime', 'Writing',
  'Board Games', 'Pottery', 'Jazz', 'Piano', 'Vinyl Records',
  'Fitness', 'Meditation', 'Theater', 'Camping', 'Wine',
];
